### ISSUE TITLE
MODELO DE NEGOCIOS

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-modelo-de-negocios-tecno-power#2]
[PRACTICA_MODELO_DE_NEGOCIOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-modelo-de-negocios-tecno-power/files/7369795/PRACTICA_MODELO_DE_NEGOCIOS.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION: 18/20

**Comment by josealfredo79** [comment]
bien hecho y revisado
